services:
  docucraft:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - FIREBASE_KEY_PATH=firebase-key.json
      - GCP_PROJECT_ID=your-gcp-project-id
      - GCP_BUCKET_NAME=your-bucket-name
      - GCP_REGION=us-central1
      - GEMINI_MODEL=gemini-pro
      - LATEX_COMPILER=pdflatex
      - LATEX_TIMEOUT=30
      - SECRET_KEY=dev-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MAX_FILE_SIZE=10485760
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - docucraft
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: docucraft-network
