services:
  docucraft-dev:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - PYTHONPATH=/app
      - FIREBASE_KEY_PATH=firebase-key.json
      - GCP_PROJECT_ID=your-gcp-project-id
      - GCP_BUCKET_NAME=your-bucket-name
      - GCP_REGION=us-central1
      - GEMINI_MODEL=gemini-pro
      - LATEX_COMPILER=pdflatex
      - LATEX_TIMEOUT=30
      - SECRET_KEY=dev-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MAX_FILE_SIZE=10485760
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: docucraft-dev-network
